draw_set_color(16777215);
draw_set_font(1);
stringo= "";
if(global.flag[66] == 1) stringo= "DATE POWER";
if(global.flag[66] == 0) stringo= "FRIENDSHIP";
draw_text(x, y - 36, string_hash_to_newline(stringo));
draw_rectangle(x - 3, y - 3, x + maxlength + 3, y + 27, 0);
draw_set_color(0);
draw_rectangle(x - 1, y - 1, x + maxlength + 1, y + 25, 0);
draw_set_color(8421504);
draw_rectangle(x, y, x + maxlength, y + 24, 0);
siner++;
value= 200 + sin(siner * 10 * length / maxlength / 10) * (20 + 35 * length / maxlength);
if(value > 255) value= 255;
if(value < 180) value= 180;
draw_set_color(make_color_hsv(160, 255, value));
draw_rectangle(x, y, x + length, y + 24, 0);
if(ideallength > length) length++;
if(ideallength < length) length--;

